ProjectilePrefabs = {
    -- "BUILT-IN/prefab/vehicle/land/boxtruck_fish_blue_light.xml",
    -- "BUILT-IN/prefab/vehicle/land/boxtruck_ontarget_white.xml",
    -- "BUILT-IN/prefab/vehicle/land/boxtruck_white.xml",
    "BUILT-IN/prefab/vehicle/land/bumpercar_blue.xml",
    "BUILT-IN/prefab/vehicle/land/bumpercar_green.xml",
    "BUILT-IN/prefab/vehicle/land/bumpercar_red.xml",
    "BUILT-IN/prefab/vehicle/land/bumpercar_yellow.xml",
    -- "BUILT-IN/prefab/vehicle/land/bus_red_white.xml",
    -- "BUILT-IN/prefab/vehicle/land/cementtruck_gray_light.xml",
    "BUILT-IN/prefab/vehicle/land/classic_blue.xml",
    "BUILT-IN/prefab/vehicle/land/classic_pink.xml",
    -- "BUILT-IN/prefab/vehicle/land/combine_harvester_yellow.xml",
    -- "BUILT-IN/prefab/vehicle/land/crane_big_yellow.xml",
    -- "BUILT-IN/prefab/vehicle/land/crane_medium_yellow.xml",
    "BUILT-IN/prefab/vehicle/land/dumptruck_yellow.xml",
    "BUILT-IN/prefab/vehicle/land/excavator_big_yellow.xml",
    "BUILT-IN/prefab/vehicle/land/excavator_medium_yellow.xml",
    -- "BUILT-IN/prefab/vehicle/land/foodtruck_burger.xml",
    -- "BUILT-IN/prefab/vehicle/land/foodtruck_grill.xml",
    -- "BUILT-IN/prefab/vehicle/land/foodtruck_icecream.xml",
    -- "BUILT-IN/prefab/vehicle/land/foodtruck_pizza.xml",
    -- "BUILT-IN/prefab/vehicle/land/foodtruck_taco.xml",
    "BUILT-IN/prefab/vehicle/land/forklift_big_yellow.xml",
    "BUILT-IN/prefab/vehicle/land/forklift_small_yellow.xml",
    "BUILT-IN/prefab/vehicle/land/forklift_small_yellow_electric.xml",
    "BUILT-IN/prefab/vehicle/land/frontloader_yellow.xml",
    -- "BUILT-IN/prefab/vehicle/land/gelato_truck_yellow_white.xml",
    "BUILT-IN/prefab/vehicle/land/generic_blue_light.xml",
    "BUILT-IN/prefab/vehicle/land/generic_sedan_red.xml",
    "BUILT-IN/prefab/vehicle/land/generic_sedan_white_stripes.xml",
    "BUILT-IN/prefab/vehicle/land/generic_small_blue.xml",
    "BUILT-IN/prefab/vehicle/land/generic_small_epa_pink.xml",
    "BUILT-IN/prefab/vehicle/land/generic_stationwagon_blue_dark.xml",
    "BUILT-IN/prefab/vehicle/land/generic_stationwagon_yellow.xml",
    "BUILT-IN/prefab/vehicle/land/generic_taxi_yellow.xml",
    -- "BUILT-IN/prefab/vehicle/land/military_atv_green.xml",
    -- "BUILT-IN/prefab/vehicle/land/military_atv_green_launcher.xml",
    -- "BUILT-IN/prefab/vehicle/land/military_tank_green.xml",
    -- "BUILT-IN/prefab/vehicle/land/military_tracked_green.xml",
    -- "BUILT-IN/prefab/vehicle/land/military_tracked_green_trailer.xml",
    -- "BUILT-IN/prefab/vehicle/land/military_truck_green.xml",
    -- "BUILT-IN/prefab/vehicle/land/monstertruck_black_flames.xml",
    -- "BUILT-IN/prefab/vehicle/land/monstertruck_pink.xml",
    "BUILT-IN/prefab/vehicle/land/musclecar_black.xml",
    "BUILT-IN/prefab/vehicle/land/musclecar_green.xml",
    "BUILT-IN/prefab/vehicle/land/pickup_black.xml",
    "BUILT-IN/prefab/vehicle/land/pickup_covered_green.xml",
    "BUILT-IN/prefab/vehicle/land/pickup_red.xml",
    "BUILT-IN/prefab/vehicle/land/pickup_white_stripes.xml",
    "BUILT-IN/prefab/vehicle/land/policecar.xml",
    "BUILT-IN/prefab/vehicle/land/racingcar_red.xml",
    "BUILT-IN/prefab/vehicle/land/racingcar_yellow.xml",
    -- "BUILT-IN/prefab/vehicle/land/semitruck_eu_green.xml",
    -- "BUILT-IN/prefab/vehicle/land/semitruck_us_nobel.xml",
    -- "BUILT-IN/prefab/vehicle/land/semitruck_us_propane.xml",
    -- "BUILT-IN/prefab/vehicle/land/semitruck_us_red.xml",
    "BUILT-IN/prefab/vehicle/land/skylift_green.xml",
    "BUILT-IN/prefab/vehicle/land/snowplow_yellow.xml",
    "BUILT-IN/prefab/vehicle/land/sportscar_green.xml",
    "BUILT-IN/prefab/vehicle/land/sportscar_pink.xml",
    "BUILT-IN/prefab/vehicle/land/suv_adventure_blue_light.xml",
    "BUILT-IN/prefab/vehicle/land/suv_open_military.xml",
    "BUILT-IN/prefab/vehicle/land/suv_open_red.xml",
    "BUILT-IN/prefab/vehicle/land/suv_open_tuned_black.xml",
    "BUILT-IN/prefab/vehicle/land/suv_silver.xml",
    -- "BUILT-IN/prefab/vehicle/land/telehandler_blue.xml",
    "BUILT-IN/prefab/vehicle/land/tractor_teal.xml",
    "BUILT-IN/prefab/vehicle/land/truck_cars_white.xml",
    "BUILT-IN/prefab/vehicle/land/truxterminator.xml",
    "BUILT-IN/prefab/vehicle/land/truxterminator_barebone.xml",
    "BUILT-IN/prefab/vehicle/land/van_flatbed_white.xml",
    "BUILT-IN/prefab/vehicle/land/van_gardener_red_trailer.xml",
    "BUILT-IN/prefab/vehicle/land/van_lightning_blue_light_trailer.xml",
    "BUILT-IN/prefab/vehicle/land/van_lts_beige.xml",
    "BUILT-IN/prefab/vehicle/land/van_lts_new_white.xml",
    "BUILT-IN/prefab/vehicle/land/van_movers_blue_light.xml",
    "BUILT-IN/prefab/vehicle/land/van_radio.xml",
    "BUILT-IN/prefab/vehicle/land/van_white.xml",
    "BUILT-IN/prefab/vehicle/land/van_woofingwolf.xml",
    "BUILT-IN/prefab/vehicle/land/van_yellow.xml",
}